version: '3.3'

services:
  db:
    image: postgres
    container_name: container-postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: bot_detector
    ports:
      - 5432:5432
  
  pgadmin:
    restart: always
    container_name: container-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=qwerty
    ports:
      - "5050:80"
    depends_on:
      - db
